### ISSUE TITLE
cant compile EtwExplorer for visual studio 2022

### ISSUE THREAD

**Issue by idoSinai** [zodiacon/EtwExplorer#11]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'EtwManifestParsing' could not be found (are you missing a using directive or an assembly reference?)	EtwExplorer	D:\projects\EtwExplorer\EtwExplorer\ViewModels\KeywordsTabViewModel.cs	1	Active

for example and more

**Comment by EsharkyTheGreat** [comment]
Hey @idoSinai may I know how you solved this error as I'm facing the same
